services:
  server:
    build: ./server
    ports:
      - '3001:3001'
    volumes:
      - ./server/db.sqlite3:/usr/src/app/db.sqlite3
    env_file:
      - ./.env

  client:
    build: ./client
    ports:
      - '3000:80'
    depends_on:
      - server

networks:
  default:
    driver: bridge
